catalogMode: prefer
shellEmulator: true

packages:
  - docs
  - playground
  - packages/**
  - examples/**

overrides:
  "@types/node": 22.19.3
  vue: 3.4.38

catalogs:
  build:
    "@rollup/plugin-commonjs": ^29.0.0
    "@rollup/plugin-node-resolve": ^16.0.3
    "@rollup/plugin-terser": ^0.4.4
    "@uni-helper/plugin-uni": ^0.1.0
    "@uni-helper/vite-plugin-uni-components": ^0.2.3
    "@uni-helper/vite-plugin-uni-manifest": ^0.2.12
    "@uni-helper/vite-plugin-uni-pages": ^0.3.22
    "@uni-ku/unplugin-keep-comments": ^0.1.0
    rollup: ^4.54.0
    tsdown: ^0.18.3
    unplugin-auto-import: ^20.3.0
    vite: ^5.4.21
    vite-plugin-inspect: ~0.8.9
    vite-plugin-uni-polyfill: ^0.1.0
  cli:
    "@antfu/ni": ^28.0.0
    "@uni-helper/unh": ^0.2.10
    bumpp: ^10.3.2
    minimist: ^1.2.8
    pncat: ^0.7.7
  dcloudio:
    "@dcloudio/types": ^3.4.28
    "@dcloudio/uni-app": 3.0.0-4080720251210001
    "@dcloudio/uni-app-harmony": 3.0.0-4080720251210001
    "@dcloudio/uni-app-plus": 3.0.0-4080720251210001
    "@dcloudio/uni-automator": 3.0.0-4080720251210001
    "@dcloudio/uni-cli-shared": 3.0.0-4080720251210001
    "@dcloudio/uni-components": 3.0.0-4080720251210001
    "@dcloudio/uni-h5": 3.0.0-4080720251210001
    "@dcloudio/uni-mp-alipay": 3.0.0-4080720251210001
    "@dcloudio/uni-mp-baidu": 3.0.0-4080720251210001
    "@dcloudio/uni-mp-jd": 3.0.0-4080720251210001
    "@dcloudio/uni-mp-kuaishou": 3.0.0-4080720251210001
    "@dcloudio/uni-mp-lark": 3.0.0-4080720251210001
    "@dcloudio/uni-mp-qq": 3.0.0-4080720251210001
    "@dcloudio/uni-mp-toutiao": 3.0.0-4080720251210001
    "@dcloudio/uni-mp-weixin": 3.0.0-4080720251210001
    "@dcloudio/uni-mp-xhs": 3.0.0-4080720251210001
    "@dcloudio/uni-quickapp-webview": 3.0.0-4080720251210001
    "@dcloudio/uni-stacktracey": 3.0.0-4080720251210001
    "@dcloudio/vite-plugin-uni": 3.0.0-4080720251210001
  dev:
    "@vue/runtime-core": ~3.4.38
  docs:
    vitepress: ^1.6.4
    vitepress-plugin-group-icons: ^1.6.5
    vitepress-plugin-llms: ^1.10.0
  frontend:
    color: ^5.0.3
    echarts: ^6.0.0
    monaco-editor: ~0.54.0
    pinia: 2.2.4
    vue: ~3.4.38
    wot-design-uni: ^1.13.0
  icons:
    "@iconify-json/carbon": ^1.2.15
  lint:
    eslint: ^9.39.2
    lint-staged: ^16.2.7
    simple-git-hooks: ^2.13.1
    stylelint: ^16.26.1
  node:
    "@clack/prompts": ^0.11.0
    chalk: ^5.6.2
    consola: ^3.4.2
    fs-extra: ^11.3.3
    rimraf: ^6.1.2
  parser:
    oxc-parser: ~0.106.0
  script:
    esno: ^4.8.0
  server:
    nitropack: ^2.12.9
  style:
    sass: ~1.78.0
    uni-unocss: ~1.0.0-beta.3
  test:
    vitest: ^4.0.16
  tsc:
    typescript: ~5.9.3
    vue-tsc: ~3.1.8
  types:
    "@mini-types/alipay": ^3.0.14
    "@types/fs-extra": ^11.0.4
    "@types/minimist": ^1.2.5
    "@types/node": ^22.19.3
    "@uni-helper/uni-app-types": ~1.0.0-alpha.7
    miniprogram-api-typings: ^4.1.2
  utils:
    "@vueuse/core": ^12.8.2
    es-toolkit: ^1.43.0
    magic-string: ^0.30.21
  xiaohe:
    "@xiaohe01/eslint-config": ^4.1.0
    "@xiaohe01/stylelint-config": ^3.1.0
    "@xiaohe01/tsconfig": ^3.1.0

onlyBuiltDependencies:
  - "@parcel/watcher"
  - core-js
  - esbuild
  - simple-git-hooks
  - vue-demi