packages:
  - docs
  - playground
  - packages/**
  - examples/**
overrides:
  mkdist: 2.3.0
  vue: 3.4.38
catalogs:
  build:
    '@uni-helper/vite-plugin-uni-components': ^0.2.1
    '@uni-helper/vite-plugin-uni-manifest': ^0.2.8
    '@uni-helper/vite-plugin-uni-pages': ^0.3.15
    unbuild: ~3.5.0
    unplugin-auto-import: ^20.1.0
    vite: ^5.4.20
    vite-plugin-inspect: ~0.8.9
    vite-plugin-uni-polyfill: ^0.1.0
    vitepress: ^1.6.4
    vitepress-plugin-group-icons: ^1.6.3
    vitepress-plugin-llms: ^1.7.5
  cli:
    bumpp: ^10.2.3
    pncat: ^0.5.4
  dcloudio:
    '@dcloudio/types': ^3.4.21
    '@dcloudio/uni-app': 3.0.0-4070620250821001
    '@dcloudio/uni-app-harmony': 3.0.0-4070620250821001
    '@dcloudio/uni-app-plus': 3.0.0-4070620250821001
    '@dcloudio/uni-automator': 3.0.0-4070620250821001
    '@dcloudio/uni-cli-shared': 3.0.0-4070620250821001
    '@dcloudio/uni-components': 3.0.0-4070620250821001
    '@dcloudio/uni-h5': 3.0.0-4070620250821001
    '@dcloudio/uni-mp-alipay': 3.0.0-4070620250821001
    '@dcloudio/uni-mp-baidu': 3.0.0-4070620250821001
    '@dcloudio/uni-mp-jd': 3.0.0-4070620250821001
    '@dcloudio/uni-mp-kuaishou': 3.0.0-4070620250821001
    '@dcloudio/uni-mp-lark': 3.0.0-4070620250821001
    '@dcloudio/uni-mp-qq': 3.0.0-4070620250821001
    '@dcloudio/uni-mp-toutiao': 3.0.0-4070620250821001
    '@dcloudio/uni-mp-weixin': 3.0.0-4070620250821001
    '@dcloudio/uni-mp-xhs': 3.0.0-4070620250821001
    '@dcloudio/uni-quickapp-webview': 3.0.0-4070620250821001
    '@dcloudio/uni-stacktracey': 3.0.0-4070620250821001
    '@dcloudio/vite-plugin-uni': 3.0.0-4070620250821001
  dev:
    '@antfu/ni': ^26.0.1
    '@mini-types/alipay': ^3.0.14
    '@uni-helper/plugin-uni': ^0.1.0
    '@uni-helper/uni-app-types': ^1.0.0-alpha.6
    '@xiaohe01/tsconfig': ^2.0.0
    miniprogram-api-typings: ^4.1.0
    oxc-parser: ^0.90.0
    typescript: ~5.8.3
  frontend:
    '@vue/runtime-core': ~3.4.38
    echarts: ^5.6.0
    pinia: 2.2.4
    vue: ~3.4.38
    vue-tsc: ~2.1.10
    wot-design-uni: ^1.12.4
  icons:
    '@iconify-json/carbon': ^1.2.13
  lint:
    '@xiaohe01/eslint-config': ^2.3.0
    '@xiaohe01/stylelint-config': ^2.4.0
    eslint: ^9.36.0
    lint-staged: ^16.1.6
    simple-git-hooks: ^2.13.1
    stylelint: ^16.24.0
  node:
    chalk: ^5.6.2
    consola: ^3.4.2
    execa: ^9.6.0
    fs-extra: ^11.3.2
    rimraf: ^6.0.1
  script:
    esno: ^4.8.0
  style:
    '@uni-helper/unocss-preset-uni': ^0.2.11
    sass: ~1.78.0
    unocss: ~66.0.0
    unocss-applet: ^0.11.0
  test:
    vitest: ^3.2.4
  types:
    '@types/fs-extra': ^11.0.4
    '@types/lodash-es': ^4.17.12
  utils:
    '@antfu/utils': ^9.2.1
    '@vueuse/core': ^12.8.2
    lodash-es: ^4.17.21
onlyBuiltDependencies:
  - '@uni-helper/unocss-preset-uni'
  - core-js
  - esbuild
  - pncat
  - simple-git-hooks
  - vue-demi