packages:
  - docs
  - playground
  - packages/**
  - examples/**
overrides:
  pinia: 2.2.4
catalogs:
  build:
    '@dcloudio/vite-plugin-uni': 3.0.0-4070520250711001
    '@uni-helper/vite-plugin-uni-components': ^0.2.0
    '@uni-helper/vite-plugin-uni-manifest': ^0.2.8
    '@uni-helper/vite-plugin-uni-pages': ^0.2.29
    unbuild: ^3.6.0
    unplugin-auto-import: ^19.3.0
    vite: ^5.4.19
    vite-plugin-uni-polyfill: ^0.1.0
    vitepress: ^1.6.3
    vitepress-plugin-group-icons: ^1.6.1
    vitepress-plugin-llms: ^1.7.1
  cli:
    bumpp: ^10.2.0
    pncat: ^0.2.6
  dev:
    '@antfu/ni': ^25.0.0
    '@antfu/utils': ^9.2.0
    '@dcloudio/types': ^3.4.16
    '@dcloudio/uni-automator': 3.0.0-4070520250711001
    '@dcloudio/uni-cli-shared': 3.0.0-4070520250711001
    '@dcloudio/uni-stacktracey': 3.0.0-4070520250711001
    '@mini-types/alipay': ^3.0.14
    '@uni-helper/uni-app-types': ^1.0.0-alpha.6
    '@vue/runtime-core': ~3.4.38
    '@xiaohe01/tsconfig': ^2.0.0
    miniprogram-api-typings: ^4.1.0
    typescript: ~5.7.3
    vue-tsc: ~2.1.10
  frontend:
    echarts: ^5.6.0
    pinia: ~2.2.4
    vue: ~3.4.38
  icons:
    '@iconify-json/carbon': ^1.2.11
  lint:
    '@xiaohe01/eslint-config': ^1.11.0
    '@xiaohe01/stylelint-config': ^2.4.0
    eslint: ^9.31.0
    lint-staged: ^16.1.2
    simple-git-hooks: ^2.13.0
    stylelint: ^16.22.0
  node:
    chalk: ^5.4.1
    consola: ^3.4.2
    execa: ^9.6.0
    fs-extra: ^11.3.0
    rimraf: ^6.0.1
  prod:
    '@dcloudio/uni-app': 3.0.0-4070520250711001
    '@dcloudio/uni-app-harmony': 3.0.0-4070520250711001
    '@dcloudio/uni-app-plus': 3.0.0-4070520250711001
    '@dcloudio/uni-components': 3.0.0-4070520250711001
    '@dcloudio/uni-h5': 3.0.0-4070520250711001
    '@dcloudio/uni-mp-alipay': 3.0.0-4070520250711001
    '@dcloudio/uni-mp-baidu': 3.0.0-4070520250711001
    '@dcloudio/uni-mp-jd': 3.0.0-4070520250711001
    '@dcloudio/uni-mp-kuaishou': 3.0.0-4070520250711001
    '@dcloudio/uni-mp-lark': 3.0.0-4070520250711001
    '@dcloudio/uni-mp-qq': 3.0.0-4070520250711001
    '@dcloudio/uni-mp-toutiao': 3.0.0-4070520250711001
    '@dcloudio/uni-mp-weixin': 3.0.0-4070520250711001
    '@dcloudio/uni-mp-xhs': 3.0.0-4070520250711001
    '@dcloudio/uni-quickapp-webview': 3.0.0-4070520250711001
    wot-design-uni: ^1.11.0
  script:
    esno: ^4.8.0
  style:
    '@uni-helper/unocss-preset-uni': ^0.2.11
    sass: ~1.78.0
    unocss: ~66.0.0
    unocss-applet: ^0.10.0
  test:
    vitest: ^3.2.4
  types:
    '@types/fs-extra': ^11.0.4
    '@types/lodash-es': ^4.17.12
  utils:
    '@vueuse/core': ^12.8.2
    lodash-es: ^4.17.21
onlyBuiltDependencies:
  - '@uni-helper/unocss-preset-uni'
  - core-js
  - esbuild
  - simple-git-hooks
  - vue-demi