name: Issue Reply

permissions:
  issues: write

on:
  issues:
    types:
      - labeled

jobs:
  issue-reply:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - label: 🖱️ need reproduce
            content: |
              你好 @${{ github.event.issue.user.login }}，我们需要你提供一个最小重现实例以便于我们帮你排查问题，可以通过 [create-uni](https://uni-helper.js.org/create-uni) 快速创建项目，示例如下：

              ```shell
              # 直接创建项目
              pnpm create uni@latest uni-echarts-repro --ts -p import -m uniEcharts --eslint

              # 或者手动选择需要的模块
              pnpm create uni@latest
              ```

              注意，请确保 `uni-echarts` 为最新版本。
          - label: 🕒 no response
            content: 由于长时间未收到反馈，此 issue 将被关闭，如果有新的进展可以随时重新打开。
    steps:
      - name: Reply by label
        if: github.event.label.name == matrix.label
        uses: actions-cool/issues-helper-backup@d65454423c6fbbd20026b9b499d403f79422ac69
        with:
          actions: create-comment
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: ${{ matrix.content }}